### ISSUE TITLE
Install failure on debian stretch. It depends package is libreadline6.

### ISSUE THREAD

**Issue by d6rkaiz** [haconiwa/haconiwa#120] opened 2017-06-28 16:10 UTC
haconiwa に興味でてきましたのでDebian9にてインストールしようとしたところ、libreadline6が必要と警告がでたのですがDebian9にはlibreadline6は無くなっておりlibreadlineは5もしくは7での提供のみとなってるようですので報告します。他に必要な情報あればご指摘ください。

install log is here.

```
$ curl -s https://packagecloud.io/install/repositories/udzura/haconiwa/script.deb.sh | sudo bash
Detected operating system as debian/stretch.
Checking for curl...
Detected curl...
Running apt-get update... done.
Installing debian-archive-keyring which is needed for installing
apt-transport-https on many Debian systems.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/udzura_haconiwa.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.
$ sudo apt-get install haconiwa=0.8.7-1
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 haconiwa : Depends: libreadline6 (>= 6.0) but it is not installable
E: Unable to correct problems, you have held broken packages.

$ sudo apt install libreadline6
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libreadline6 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libreadline6' has no installation candidate
```

already installed libreadline is 7.

```
$ dpkg --list|grep libreadline
ii  libreadline7:amd64            7.0-3                          amd64        GNU readline and history libraries, run-time libraries
```

I searched for libreadline but libreadline 6 was missing.

```
$ apt search libreadline
Sorting... Done
Full Text Search... Done
cupt/stable 2.9.9 amd64
  flexible package manager -- console interface

libreadline-dev/stable 7.0-3 amd64
  GNU readline and history libraries, development files

libreadline-gplv2-dev/stable 5.2+dfsg-3+b1 amd64
  GNU readline and history libraries, development files

libreadline-java/stable 0.8.0.1+dfsg-5 amd64
  GNU readline and BSD editline wrappers for Java

libreadline-java-doc/stable 0.8.0.1+dfsg-5 all
  API docs for readline/editline wrappers for Java

libreadline5/stable 5.2+dfsg-3+b1 amd64
  GNU readline and history libraries, run-time libraries

libreadline5-dbg/stable 5.2+dfsg-3+b1 amd64
  GNU readline and history libraries, debugging libraries

libreadline7/stable,now 7.0-3 amd64 [installed]
  GNU readline and history libraries, run-time libraries

libreadline7-dbg/stable 7.0-3 amd64
  GNU readline and history libraries, debugging libraries
```

**Comment by udzura** [comment] 2017-06-29 01:17
@d6rkaiz is saying:

* There is no libreadline6 package in Debian stretch. 5 or 7 exists.
* But `haconiwa` package seems to be dependent to libreadline **6**...

**Comment by udzura** [comment] 2017-06-29 01:28
The answer is:

* Now haconiwa deb packages are built on an [`ubuntu:trusty` image](https://github.com/haconiwa/haconiwa/blob/master/packages/dockerfiles/Dockerfile.debian#L2), where they use readline 6: https://packages.ubuntu.com/trusty/readline-common
  * Also, xenial using the 6 https://packages.ubuntu.com/xenial/readline-common
* And now `hacoirb` binary is dependent to libreadline. But `haconiwa` itself is not.

```
vagrant@localhost:~$ haconiwa version
haconiwa: v0.8.7
vagrant@localhost:~$ ldd `which haconiwa`
        linux-vdso.so.1 =>  (0x00007ffcd5989000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fcb35cb6000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fcb35a99000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fcb35890000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fcb354c6000)
        /lib64/ld-linux-x86-64.so.2 (0x000055f8adf5e000)
vagrant@localhost:~$ ldd `which hacoirb`
        linux-vdso.so.1 =>  (0x00007ffd46dce000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f672ee58000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f672ec3b000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f672ea32000)
        libreadline.so.6 => /lib/x86_64-linux-gnu/libreadline.so.6 (0x00007f672e7ec000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f672e422000)
        /lib64/ld-linux-x86-64.so.2 (0x000055a59c660000)
        libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f672e1f8000)
```

* So I'm planning to create and test `debian:9` Dockerfile to build an image for deb packages. You can set up these... and make PR :)
* At this time you might do:
  * Try [binary file](https://github.com/haconiwa/haconiwa/releases/tag/v0.8.7) but `hacoirb` may no work.
  * Use debian squeeze or ubuntu xenial... (Now xenial is a first distro to build and test)

なかなか周辺エコシステムの整備が追いつかず、ご苦労をおかけします。貢献いただけるのは大歓迎です ;)

**Comment by d6rkaiz** [comment] 2017-06-29 03:48
The purpose of this issue is to let you know. there are no problems.
I already tried the binary version.
ok, I will try to make a PR if possible.

thanks.

英語は読むことはだいたい苦痛はないのですが、書くほうはまだまだスキル不足でご面倒おかけしました。

**Comment by udzura** [comment] 2017-06-29 03:54
The issue is helpful!! Thanks!!

I will close this after `debian:9` build environment will be ready.

**Comment by udzura** [comment] 2017-07-01 07:16
Would you try this? https://packagecloud.io/udzura/haconiwa/packages/debian/stretch/haconiwa_0.8.7-1_amd64.deb

**Comment by d6rkaiz** [comment] 2017-07-01 08:32
sorry for late and thank you for quick work.
I tried it immediately.

```
$ curl -s https://packagecloud.io/install/repositories/udzura/haconiwa/script.deb.sh | sudo bash
Detected operating system as debian/stretch.
Checking for curl...
Detected curl...
Running apt-get update... done.
Installing debian-archive-keyring which is needed for installing
apt-transport-https on many Debian systems.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/udzura_haconiwa.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.
$ sudo apt-get install haconiwa=0.8.7-1
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  haconiwa
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 611 kB of archives.
After this operation, 6,228 kB of additional disk space will be used.
Get:1 https://packagecloud.io/udzura/haconiwa/debian stretch/main amd64 haconiwa amd64 0.8.7-1 [611 kB]
Fetched 611 kB in 2s (247 kB/s)
Selecting previously unselected package haconiwa.
(Reading database ... 28927 files and directories currently installed.)
Preparing to unpack .../haconiwa_0.8.7-1_amd64.deb ...
Unpacking haconiwa (0.8.7-1) ...
Setting up haconiwa (0.8.7-1) ...
```

Installation is completed. thank you!!

**Comment by udzura** [comment] 2017-07-01 08:33
Good!!! Thanks reporting 😄

**Closed by udzura** 2017-07-01 08:33 UTC
